name: Setup node and pnpm
description: Setup node and install dependencies using pnpm
inputs:
  use_lockfile:
    description: 'Whether to use the lockfile vs latest floating dependencies'
    required: false
    default: true

  node-version:
    description: 'The node version to use'
    required: false
    default: 20
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: false
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '${{ inputs.node-version }}'
        registry-url: 'https://registry.npmjs.org'

