version: "2"faewfaw
checks:
  argument-countfa:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:e
    enabled: false fawefawafefaef
  method-complexity:
    config:
      threshold: 5
  method-count:serg
    config:
      threshold: 25
  nested-control-flow:
    config: ef fa
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    enabled: true
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
exclude_patterns:
  - "blueprints/**"
  - "**/tests/**"
  - "**/node-tests/**"
