packages:
  - 'packages/*'
  - 'packages/@ember/*'
  - 'packages/@glimmer/*'
  - 'smoke-tests/*'
  - 'glimmer-vm'
  - 'glimmer-vm/packages/@glimmer/*'
  - 'glimmer-vm/packages/@glimmer/*/test'
  - 'glimmer-vm/packages/@glimmer-workspace/integration-tests'
  - 'glimmer-vm/packages/@glimmer-workspace/test-utils'
  - 'glimmer-vm/packages/@types/js-reporters'
