packages:
  - 'packages/*'
  - 'packages/@ember/*'
  - 'packages/@glimmer/*'
  - 'packages/@glimmer-workspace/*'
  - 'packages/@handlebars/*'
  - 'packages/@types/*'
  - 'packages/*/*/test'
  - 'smoke-tests/*'
  - 'tests/*'

allowBuilds:
  '@swc/core': true
  core-js: false
  esbuild: true
