packages:
  - "packages/*"
  - "packages/@ember/*"
  - "packages/@glimmer/*"
  - "packages/@glimmer-workspace/*"
  - "packages/@handlebars/*"
  - "packages/@types/*"
  - "packages/*/*/test"
  - "smoke-tests/*"
  - "tests/*"

overrides:
  "rollup": "^4.2.0"
  "ember-cli-htmlbars": "^7.0.0"
  "babel-plugin-ember-template-compilation": "^4.0.0"
  "ember-cli-babel": "^8.3.1"

onlyBuiltDependencies:
  - "@swc/core"
  - "core-js"
  - "esbuild"

patchedDependencies:
  "@tracerbench/core@8.0.1": "patches/@tracerbench__core@8.0.1.patch"
  "agadoo": "patches/agadoo.patch"

allowBuilds:
  "@swc/core": false
  esbuild: false
  core-js: false
