export type {
  AttrNamespace,
  ElementNamespace,
  InsertPosition,
  Namespace,
  NodeType,
  SerializableElement,
  SerializableNode,
  SimpleAttr,
  SimpleComment,
  SimpleDocument,
  SimpleDocumentFragment,
  SimpleElement,
  SimpleNode,
  SimpleText,
} from '@simple-dom/interface';
