// Universal WASM wrapper — works in both Node.js and browsers.
//
// Imports the web-target WASM wrapper (which uses standard ESM),
// then synchronously initializes it with the WASM bytes loaded from
// a base64-encoded string. Generated by build.sh.

import { initSync, parseTemplate, parseTemplateToJson } from './standalone/glimmer_template_parser.js';
import { WASM_BYTES_BASE64 } from './wasm-bytes.mjs';

function base64ToUint8Array(base64) {
  if (typeof Buffer !== 'undefined') {
    return new Uint8Array(Buffer.from(base64, 'base64'));
  }
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

// Initialize the WASM module synchronously with inlined bytes.
// Works in both Node.js and browser contexts.
initSync({ module: base64ToUint8Array(WASM_BYTES_BASE64) });

export { parseTemplate, parseTemplateToJson };
