// GENERATED: 2011-04-30 21:44:14 -0700
// This file is automatically generated by spade.  To update run 
// 'spade update'. To use this file, reference it in your HTML file.  Base 
// sure that your base URL is to the top level directory containing all of 
// your files.

/*globals spade */
//@ begin boot
(function() {
  // load spade itself
  var script = document.createElement('script');
  script.src = ".spade/boot/spade.js";
  script.onload = function() {

    // Register remaining packages with spade
spade.register("sproutcore-preprocessor", {
  "name": "sproutcore-preprocessor",
  "summary": "SproutCore Preprocessor",
  "description": "Pre-processor to handle sc_super",
  "homepage": "http://sproutcore.com",
  "author": "Charles Jolley",
  "version": "0.0.2",
  "plugin:preprocessors": [
    "sproutcore-preprocessor/preprocessor"
  ],
  "plugin:formats": {
    "css": "sproutcore-preprocessor/css"
  },
  "directories": {
    "lib": "./lib"
  },
  "bin": {
    "chance": "./bin/chance"
  },
  "sync": true,
  "root": ".spade/packages/sproutcore-preprocessor",
  "files": [
    "lib/css.js",
    "lib/main.js",
    "lib/preprocessor.js",
    "lib/sc_static.js"
  ]
});

spade.register("sproutcore-runtime", {
  "name": "sproutcore-runtime",
  "summary": "SproutCore Runtime",
  "description": "The base SproutCore runtime. Essential for all SproutCore apps.",
  "homepage": "http://sproutcore.com",
  "author": "Charles Jolley",
  "version": "2.0",
  "dependencies": {
    "sproutcore-preprocessor": "~> 0.0.2"
  },
  "plugin:preprocessors": [
    "sproutcore-preprocessor/preprocessor"
  ],
  "directories": {
    "lib": "./lib",
    "tests": "./tests"
  },
  "root": ".",
  "sync": true,
  "files": [
    "lib/ext/array.js",
    "lib/ext/function.js",
    "lib/ext/string.js",
    "lib/ext.js",
    "lib/license.js",
    "lib/main.js",
    "lib/mixins/array.js",
    "lib/mixins/comparable.js",
    "lib/mixins/copyable.js",
    "lib/mixins/enumerable.js",
    "lib/mixins/freezable.js",
    "lib/mixins/observable.js",
    "lib/mixins.js",
    "lib/private/chain_observer.js",
    "lib/private/observer_queue.js",
    "lib/private/observer_set.js",
    "lib/private/property_chain.js",
    "lib/private.js",
    "lib/runtime.js",
    "lib/system/binding.js",
    "lib/system/enumerator.js",
    "lib/system/function.js",
    "lib/system/index_set.js",
    "lib/system/json.js",
    "lib/system/logger.js",
    "lib/system/object.js",
    "lib/system/run_loop.js",
    "lib/system/set.js",
    "lib/system/string.js",
    "lib/system.js",
    "lib/test_suites/array/base.js",
    "lib/test_suites/array/indexOf.js",
    "lib/test_suites/array/insertAt.js",
    "lib/test_suites/array/objectAt.js",
    "lib/test_suites/array/popObject.js",
    "lib/test_suites/array/pushObject.js",
    "lib/test_suites/array/removeAt.js",
    "lib/test_suites/array/removeObject.js",
    "lib/test_suites/array/replace.js",
    "lib/test_suites/array/shiftObject.js",
    "lib/test_suites/array/unshiftObject.js",
    "lib/test_suites/array.js",
    "tests/all.js",
    "tests/core/beget.js",
    "tests/core/clone.js",
    "tests/core/compare.js",
    "tests/core/console.js",
    "tests/core/guidFor.js",
    "tests/core/inspect.js",
    "tests/core/isArray.js",
    "tests/core/IsEqual.js",
    "tests/core/itemType.js",
    "tests/core/keys.js",
    "tests/core/makeArray.js",
    "tests/core/objectForPropertyPath.js",
    "tests/core/tupleForPropertyPath.js",
    "tests/mixins/array.js",
    "tests/mixins/comparable.js",
    "tests/mixins/enumerable/enumerable.js",
    "tests/mixins/enumerable/enumerable_observers.js",
    "tests/mixins/observable/chained.js",
    "tests/mixins/observable/observable.js",
    "tests/mixins/observable/observersForKey.js",
    "tests/mixins/observable/propertyChanges.js",
    "tests/mixins/observable/registerDependentKeys.js",
    "tests/mixins/propertyChanges.js",
    "tests/private/observer_queue/isObservingSuspended.js",
    "tests/qunit-style.css",
    "tests/qunit.js",
    "tests/system/binding.js",
    "tests/system/index_set/add.js",
    "tests/system/index_set/addEach.js",
    "tests/system/index_set/clone.js",
    "tests/system/index_set/contains.js",
    "tests/system/index_set/create.js",
    "tests/system/index_set/indexAfter.js",
    "tests/system/index_set/indexBefore.js",
    "tests/system/index_set/intersects.js",
    "tests/system/index_set/max.js",
    "tests/system/index_set/min.js",
    "tests/system/index_set/rangeStartForIndex.js",
    "tests/system/index_set/remove.js",
    "tests/system/index_set/removeEach.js",
    "tests/system/index_set/without.js",
    "tests/system/json.js",
    "tests/system/logger.js",
    "tests/system/object/base.js",
    "tests/system/object/bindings.js",
    "tests/system/object/concatenated_properties.js",
    "tests/system/object/enhance.js",
    "tests/system/observer_set.js",
    "tests/system/run_loop.js",
    "tests/system/set.js",
    "tests.html",
    "tmp/chance/0597e23d2ec8471cb95b0f368f6d5ad4.scss",
    "tmp/chance/0de570ab20f51d2c817068dc251804b4.scss",
    "tmp/chance/129c8aab321655f70a6c9eeef07c9dce.scss",
    "tmp/chance/2739d91bee264660a3ce748c6c9233e6.scss",
    "tmp/chance/3be6555ba42f871024c7f7363ec8a21b.scss",
    "tmp/chance/5b83e83a3103876b5702855300e0a468.scss",
    "tmp/chance/5e90d39838f6187fdf9af1e4e4be4840.scss",
    "tmp/chance/6934195301f453d9a6026e7f4dcd67f2.scss",
    "tmp/chance/7900de91a99b2a11cae797bd467e135b.scss",
    "tmp/chance/795f959c516beb37e4f6e2584b2239bc.scss",
    "tmp/chance/7d098ee6dbf0cded3fd4eac3129810c8.scss",
    "tmp/chance/b2a1b177c27c44fc6b4930acb25b465d.scss",
    "tmp/chance/bc168f1d9a60590bb0f1ca5e4ef2ccf6.scss",
    "tmp/sass-cache/8e3e2fb38630b4403fe82f4551a1efc08e4214f2/0597e23d2ec8471cb95b0f368f6d5ad4.scssc",
    "tmp/sass-cache/8e3e2fb38630b4403fe82f4551a1efc08e4214f2/0de570ab20f51d2c817068dc251804b4.scssc",
    "tmp/sass-cache/8e3e2fb38630b4403fe82f4551a1efc08e4214f2/129c8aab321655f70a6c9eeef07c9dce.scssc",
    "tmp/sass-cache/8e3e2fb38630b4403fe82f4551a1efc08e4214f2/2739d91bee264660a3ce748c6c9233e6.scssc",
    "tmp/sass-cache/8e3e2fb38630b4403fe82f4551a1efc08e4214f2/3be6555ba42f871024c7f7363ec8a21b.scssc",
    "tmp/sass-cache/8e3e2fb38630b4403fe82f4551a1efc08e4214f2/5b83e83a3103876b5702855300e0a468.scssc",
    "tmp/sass-cache/8e3e2fb38630b4403fe82f4551a1efc08e4214f2/5e90d39838f6187fdf9af1e4e4be4840.scssc",
    "tmp/sass-cache/8e3e2fb38630b4403fe82f4551a1efc08e4214f2/6934195301f453d9a6026e7f4dcd67f2.scssc",
    "tmp/sass-cache/8e3e2fb38630b4403fe82f4551a1efc08e4214f2/7900de91a99b2a11cae797bd467e135b.scssc",
    "tmp/sass-cache/8e3e2fb38630b4403fe82f4551a1efc08e4214f2/795f959c516beb37e4f6e2584b2239bc.scssc",
    "tmp/sass-cache/8e3e2fb38630b4403fe82f4551a1efc08e4214f2/7d098ee6dbf0cded3fd4eac3129810c8.scssc",
    "tmp/sass-cache/8e3e2fb38630b4403fe82f4551a1efc08e4214f2/b2a1b177c27c44fc6b4930acb25b465d.scssc",
    "tmp/sass-cache/8e3e2fb38630b4403fe82f4551a1efc08e4214f2/bc168f1d9a60590bb0f1ca5e4ef2ccf6.scssc"
  ]
});


    // find the main module to run
    var main = null;
    var scripts = document.scripts || document.getElementsByTagName("script"),
        len = scripts.length;
    for(var idx=0;!main && idx<len;idx++) {
      main = scripts[idx].getAttribute('data-require');
    }
    scripts = null; // avoid memory leaks in IE

    if (main) spade.ready(function() { spade.require(main); });
  };

  var head = document.head || document.body || document;
  head.appendChild(script);

  script = head = null; // avoid memory leaks in IE
})();
//@ end boot
