// GENERATED: 2011-05-01 21:35:48 -0700
// This file is automatically generated by spade.  To update run 
// 'spade update'. To use this file, reference it in your HTML file.  Base 
// sure that your base URL is to the top level directory containing all of 
// your files.

/*globals spade */
//@ begin boot
(function() {
  // load spade itself
  var script = document.createElement('script');
  script.src = ".spade/boot/spade.js";
  script.onload = function() {

    // Register remaining packages with spade
spade.register("sproutcore-preprocessor", {
  "name": "sproutcore-preprocessor",
  "summary": "SproutCore Preprocessor",
  "description": "Pre-processor to handle sc_super",
  "homepage": "http://sproutcore.com",
  "author": "Charles Jolley",
  "version": "0.0.2",
  "plugin:preprocessors": [
    "sproutcore-preprocessor/preprocessor"
  ],
  "plugin:formats": {
    "css": "sproutcore-preprocessor/css"
  },
  "directories": {
    "lib": "./lib"
  },
  "bin": {
    "chance": "./bin/chance"
  },
  "sync": true,
  "root": ".spade/packages/sproutcore-preprocessor",
  "files": [
    "lib/css.js",
    "lib/main.js",
    "lib/preprocessor.js",
    "lib/sc_static.js"
  ]
});

spade.register("sproutcore-runtime", {
  "name": "sproutcore-runtime",
  "summary": "SproutCore Runtime",
  "description": "The base SproutCore runtime. Essential for all SproutCore apps.",
  "homepage": "http://sproutcore.com",
  "author": "Charles Jolley",
  "version": "2.0",
  "dependencies": {
    "sproutcore-preprocessor": "~> 0.0.2"
  },
  "plugin:preprocessors": [
    "sproutcore-preprocessor/preprocessor"
  ],
  "directories": {
    "lib": "./lib",
    "tests": "./tests"
  },
  "root": ".",
  "sync": true,
  "files": [
    "lib/ext/array.js",
    "lib/ext/function.js",
    "lib/ext/string.js",
    "lib/ext.js",
    "lib/license.js",
    "lib/main.js",
    "lib/mixins/array.js",
    "lib/mixins/comparable.js",
    "lib/mixins/copyable.js",
    "lib/mixins/enumerable.js",
    "lib/mixins/freezable.js",
    "lib/mixins/observable.js",
    "lib/mixins.js",
    "lib/private/chain_observer.js",
    "lib/private/observer_queue.js",
    "lib/private/observer_set.js",
    "lib/private/property_chain.js",
    "lib/private.js",
    "lib/runtime.js",
    "lib/system/binding.js",
    "lib/system/function.js",
    "lib/system/object.js",
    "lib/system/run_loop.js",
    "lib/system/set.js",
    "lib/system/string.js",
    "lib/system.js",
    "tests/all.js",
    "tests/core/beget.js",
    "tests/core/clone.js",
    "tests/core/compare.js",
    "tests/core/console.js",
    "tests/core/guidFor.js",
    "tests/core/inspect.js",
    "tests/core/isArray.js",
    "tests/core/IsEqual.js",
    "tests/core/itemType.js",
    "tests/core/keys.js",
    "tests/core/makeArray.js",
    "tests/core/objectForPropertyPath.js",
    "tests/core/tupleForPropertyPath.js",
    "tests/mixins/array.js",
    "tests/mixins/comparable.js",
    "tests/mixins/enumerable/enumerable.js",
    "tests/mixins/enumerable/enumerable_observers.js",
    "tests/mixins/observable/chained.js",
    "tests/mixins/observable/observable.js",
    "tests/mixins/observable/observersForKey.js",
    "tests/mixins/observable/propertyChanges.js",
    "tests/mixins/observable/registerDependentKeys.js",
    "tests/mixins/propertyChanges.js",
    "tests/private/observer_queue/isObservingSuspended.js",
    "tests/qunit-style.css",
    "tests/qunit.js",
    "tests/system/binding.js",
    "tests/system/object/base.js",
    "tests/system/object/bindings.js",
    "tests/system/object/concatenated_properties.js",
    "tests/system/object/enhance.js",
    "tests/system/observer_set.js",
    "tests/system/run_loop.js",
    "tests/system/set.js",
    "tests/test_suites/array/base.js",
    "tests/test_suites/array/indexOf.js",
    "tests/test_suites/array/insertAt.js",
    "tests/test_suites/array/objectAt.js",
    "tests/test_suites/array/popObject.js",
    "tests/test_suites/array/pushObject.js",
    "tests/test_suites/array/removeAt.js",
    "tests/test_suites/array/removeObject.js",
    "tests/test_suites/array/replace.js",
    "tests/test_suites/array/shiftObject.js",
    "tests/test_suites/array/unshiftObject.js",
    "tests/test_suites/array.js",
    "tests.html"
  ]
});


    // find the main module to run
    var main = null;
    var scripts = document.scripts || document.getElementsByTagName("script"),
        len = scripts.length;
    for(var idx=0;!main && idx<len;idx++) {
      main = scripts[idx].getAttribute('data-require');
    }
    scripts = null; // avoid memory leaks in IE

    if (main) spade.ready(function() { spade.require(main); });
  };

  var head = document.head || document.body || document;
  head.appendChild(script);

  script = head = null; // avoid memory leaks in IE
})();
//@ end boot
