name: Package Size Report

on:
  pull_request: {}

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  pkg-size-report:
    name: Package Size Report
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - uses: wyvox/pkg-size@df42795b6bc793b1558823b7b6ac6993d514ca42
        with:
          build-command: "pnpm build"
          display-size: uncompressed, brotli
          unchanged-files: hide
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
