name: Package Size Report

on:
  pull_request: {}

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  pkg-size-report:
    name: Package Size Report
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - uses: wyvox/pkg-size@4c68a40496b9dd2d228575f8738cdfa4ad277754
        with:
          build-command: "pnpm build"
          display-size: uncompressed, brotli
          unchanged-files: hide
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
