name: "Size: main"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build'
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup
        with:
          node-version: 22
      - run: pnpm build

      - name: "Get estimated sizes for production outputs"
        id: main-dev
        run: |
          mkdir -p main
          node ./bin/minify-assets.mjs > ./main/out.txt

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: sizes-main
          path: main/
          overwrite: true
