name: "Size: main"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build'
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: sudo snap install dust
      - run: pnpm build

      - name: "Get sizes for development outputs"
        id: main-dev
        run: |
          mkdir -p main
          cd dist/packages
          dust --ignore_hidden \
              --reverse --apparent-size \
              --no-percent-bars \
              --only-dir \
              --depth 20 \
            > out.txt
          cp out.txt ../../main/


      - uses: actions/upload-artifact@v4
        with:
          name: sizes-main
          path: main/
          overwrite: true
